### ISSUE TITLE
求更新维护。翻译有点问题。

### ISSUE THREAD

**Issue by MiaoWaa** [ykxVK8yL5L/pikpak-webdav#2]
![B2970EB6-466D-4C2C-AF9B-AF90A0C7F743](https://user-images.githubusercontent.com/94307085/177249850-7eeb83ab-f171-40e7-88ef-e35ce5555e9e.jpeg)
如图，翻译错了，两个用户名。

**Comment by ykxVK8yL5L** [comment]
感谢反馈  已经修正
