### ISSUE TITLE
请问为什么openwrt安装设置完显示启动了，但打不开了？

### ISSUE THREAD

**Issue by shp2814560** [ykxVK8yL5L/pikpak-webdav#3]
请问为什么openwrt安装设置完显示启动了，但打不开了？

**Comment by ykxVK8yL5L** [comment]
> 请问为什么openwrt安装设置完显示启动了，但打不开了？

没提示导致现在才看到问题 十分抱歉. 你说的太笼统了无法回答 需要你提供下运行日志 大部分情况下是网络问题. 另外账户和密码只能是邮箱密码的格式 其他的网友反馈 手机号,或谷歌登录等方式无法登陆

**Comment by ykxVK8yL5L** [comment]
大部分情况属于账号问题：目前仅支持邮箱密码形式登录，如果是谷歌邮箱的话需要到网页端设置密码绑定邮箱
