### ISSUE TITLE
什么时候能实现上传功能

### ISSUE THREAD

**Issue by ika166** [ykxVK8yL5L/pikpak-webdav#4]
什么时候能实现上传功能

**Comment by ykxVK8yL5L** [comment]
> 什么时候能实现上传功能

抱歉现在才回复  这个要看网页版的接口了  有上传接口很快可以实现  目前还不行

**Comment by pongfcnkl** [comment]
可以参考这两个项目，都有上传接口
https://github.com/52funny/pikpakupload
https://github.com/mumuchenchen/pikpak
 第二个可以在这里上传
https://mumuchenchen.github.io/pikpak/#/t

**Comment by ykxVK8yL5L** [comment]
> 可以参考这两个项目，都有上传接口
> https://github.com/52funny/pikpakupload
> https://github.com/mumuchenchen/pikpak
> 第二个可以在这里上传
> https://mumuchenchen.github.io/pikpak/#/t

感谢提供 上传功能已在开发中🙏

**Comment by ykxVK8yL5L** [comment]
> 什么时候能实现上传功能



> 可以参考这两个项目，都有上传接口
> https://github.com/52funny/pikpakupload
> https://github.com/mumuchenchen/pikpak
> 第二个可以在这里上传
> https://mumuchenchen.github.io/pikpak/#/t

感谢支持 文件上传功能已经完成 关闭issue.

**Comment by ykxVK8yL5L** [comment]
文件上传功能已经在v0.03版本实现
