### ISSUE TITLE
安装了后挂上了rclone webdav,穿了一部分文件后就一直失败

### ISSUE THREAD

**Issue by luxikakashi** [ykxVK8yL5L/pikpak-webdav#5]
开始用人rclone copy 上传速度还很快，传了一百多G吧，之后上传就一直失败

**Comment by ykxVK8yL5L** [comment]
> 

首先打开调试  看下日志  看是哪个上传错了 还是程序报错 既然上传成功过 说明程序应该是没问题的。有可能服务器限制吧  这个会在日志里显示错误信息

**Comment by luxikakashi** [comment]
![image](https://user-images.githubusercontent.com/33003445/188254347-bdf7592e-d762-40e8-bed3-a56d04da91b3.png)

**Comment by ykxVK8yL5L** [comment]
> ![image](https://user-images.githubusercontent.com/33003445/188254347-bdf7592e-d762-40e8-bed3-a56d04da91b3.png)

重启webdav 然后换个文件试下 先证明是不是程序的错误  如果程序没问题的话 就得看下文件了  这个报错的话 我还没见过 应该不是服务器反馈的错误 有可能是依赖的问题  该文件上传阿里云报错吗？

**Comment by luxikakashi** [comment]
重启了换文件都不行，阿里云没啥问题

**Comment by ykxVK8yL5L** [comment]
> 重启了换文件都不行，阿里云没啥问题

换文件 都不行 估计官方限制了吧  换官方客户端上传试试

**Comment by luxikakashi** [comment]
没办法了，我实在VPS上传的，没法用官方的啊哈哈哈‘

**Comment by ykxVK8yL5L** [comment]
> 没办法了，我实在VPS上传的，没法用官方的啊哈哈哈‘

换alist或其它webdav试下   我这和它们的实现上传的方法是不一样的。有可能是我这个webdav的问题

**Comment by ykxVK8yL5L** [comment]
> 没办法了，我实在VPS上传的，没法用官方的啊哈哈哈‘

可以参考这两个项目，都有上传接口
https://github.com/52funny/pikpakupload
https://github.com/mumuchenchen/pikpak
第二个可以在这里上传
https://mumuchenchen.github.io/pikpak/#/t

**Comment by luxikakashi** [comment]
谢谢，我试试
