### ISSUE TITLE
win10 复制文件错误，大小超过限制，无法保存

### ISSUE THREAD

**Issue by Sylphinford** [ykxVK8yL5L/pikpak-webdav#6]
在win10 上挂载
在资源管理器上复制文件会报错
![QQ截图20221022130713](https://user-images.githubusercontent.com/43917892/197336047-7be8eddb-37d6-495d-8edd-34bf82e75526.jpg)
![QQ截图20221022130506](https://user-images.githubusercontent.com/43917892/197336049-bd960db5-4f6d-4ac6-8e7f-379e0b168e2c.jpg)

但是在浏览器上打开进入，却能进入下载
![QQ截图20221022130644](https://user-images.githubusercontent.com/43917892/197336072-dd9544d5-913f-4791-9abb-3ae6150eb719.jpg)
![QQ截图20221022131258](https://user-images.githubusercontent.com/43917892/197336074-586d787f-c404-4204-8237-196ae081f7ad.jpg)

**Comment by ykxVK8yL5L** [comment]
抱歉现在才回复  试试播放看会断开不 如果播放没问题  可能是GUI的机制不同 切换alist再试下 alist可以的话就用alist吧   鉴于webdav的请求机制 我现在几乎不用这玩意 都是用网页端获取下载地址 或下载或播放
